import type { Book } from "./types"

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "Nhân sinh lục: Cuộc đời tôi",
    author: "Haruki Murakami",
    category: "Văn học",
    price: 120000,
    originalPrice: 150000,
    rating: 4.5,
    reviews: 234,
    image: "/abstract-book-cover.png",
    description: "Một tác phẩm kinh điển về cuộc sống và những trải nghiệm sâu sắc.",
    inStock: true,
    discount: 20,
  },
  {
    id: "2",
    title: "Tư duy nhanh và chậm",
    author: "Daniel Kahneman",
    category: "Tâm lý học",
    price: 150000,
    rating: 4.8,
    reviews: 567,
    image: "/psychology-book.jpg",
    description: "Khám phá cách bộ não con người hoạt động.",
    inStock: true,
  },
  {
    id: "3",
    title: "Ngôi sao trong tay tôi",
    author: "Nguyễn Nhật Ánh",
    category: "Văn học",
    price: 95000,
    rating: 4.3,
    reviews: 123,
    image: "/vietnamese-literature.jpg",
    description: "Một câu chuyện tình cảm đầy sức hấp dẫn.",
    inStock: true,
  },
  {
    id: "4",
    title: "Kinh tế học vi mô",
    author: "Paul Samuelson",
    category: "Kinh tế",
    price: 200000,
    rating: 4.6,
    reviews: 89,
    image: "/economics-book.png",
    description: "Sách cơ bản về kinh tế học.",
    inStock: true,
  },
  {
    id: "5",
    title: "Sự im lặng của chiến đấu",
    author: "Nam Cao",
    category: "Văn học",
    price: 85000,
    rating: 4.4,
    reviews: 156,
    image: "/classic-book.png",
    description: "Một tác phẩm kinh điển của nền văn học Việt Nam.",
    inStock: false,
  },
  {
    id: "6",
    title: "Bí quyết thành công",
    author: "Tony Robbins",
    category: "Phát triển bản thân",
    price: 140000,
    originalPrice: 180000,
    rating: 4.7,
    reviews: 432,
    image: "/self-help-book.png",
    description: "Hướng dẫn đạt được những mục tiêu của cuộc sống.",
    inStock: true,
    discount: 22,
  },
  {
    id: "7",
    title: "Lịch sử Việt Nam",
    author: "Trần Trọng Kim",
    category: "Lịch sử",
    price: 180000,
    rating: 4.5,
    reviews: 267,
    image: "/open-history-book.png",
    description: "Cuốn sách lịch sử Việt Nam toàn diện.",
    inStock: true,
  },
  {
    id: "8",
    title: "Khoa học dữ liệu áp dụng",
    author: "Andrew Ng",
    category: "Công nghệ",
    price: 250000,
    rating: 4.9,
    reviews: 512,
    image: "/data-science-book.jpg",
    description: "Hướng dẫn thực tế về khoa học dữ liệu.",
    inStock: true,
  },
]

export const categories = ["Văn học", "Kinh tế", "Tâm lý học", "Phát triển bản thân", "Lịch sử", "Công nghệ"]
